openstyles/stylus

- _locales/en/messages.json
- js/prefs.js
- manage.html
- manage/filters.js
- manage/manage.css
- manage/manage.js
The checkbox filters can be inverted now.
A bit unusual, though, since the entire label is a selector.
I've tried and discarded a couple of alternative solutions, and this one seems the least cluttered and most self-evident to me. Not sure about convenience as I almost never use the filters.
Please test: [invert-filters.zip](https://github.com/openstyles/stylus/archive/invert-filters.zip).
> manage: add inverted filters (disabled, external)

- _locales/en/messages.json
- manage.html
- manage/filters.js
- popup.html
- popup/popup.js
Basically like Tampermonkey's user-configurable browser shortcut to "Open the dashboard with the current tab's URL used as filter".
@narcolepticinsomniac, @Mottie, @schomery,
please test it: [manage-site-styles.zip](https://github.com/openstyles/stylus/archive/manage-site-styles.zip).
* in manager use search query like `url:https://github.com/openstyles/stylus`
* in popup `shift-click` or `right-click` on `manage` button opens it in a new tab and applies the filter
P.S. The PR is rather trivial and doesn't introduce conflicts with other pending PRs.
> URL-matching mode in manager's search and popup's manage button

- _locales/en/messages.json
- background/background.js
- background/storage.js
- background/update.js
- js/dom.js
- js/prefs.js
- manage/manage.js
- msgbox/dysfunctional.css
- msgbox/dysfunctional.html
- msgbox/dysfunctional.js
IndexedDB being blocked by Firefox is detected and a warning page is displayed instead of the actual contents.
```
Stylus cannot function because Firefox applies its website cookies policy to 
unrelated storages used by Stylus such as IndexedDB and localStorage, 
erroneously marking the secure internal moz-extension:// origin as insecure even 
though WebExtensions aren't websites and Stylus doesn't use cookies. 
You can add an exception for Stylus: 
1. open Firefox options 
2. go to Privacy & Security 
3. set History mode to 'Use custom settings' 
4. click 'Exceptions' 
5. paste our manifest URL and click 'Allow'
6. click 'Save settings'.
The actual manifest URL is shown below, also on about:debugging page.
moz-extension://006bd111-b39c-4beb-99ed-cb36302c9607/manifest.json
```
Please …
> inform when dysfunctional due to FF options

- vendor-overwrites/csslint/csslint-worker.js
Safari only supports the sticky position with a `-webkit` prefix ([ref 1](http://caniuse.com/#feat=css-sticky) &amp; [ref 2](https://developer.mozilla.org/en-US/docs/Web/CSS/position#Browser_compatibility)).
> Lint: Add -webkit-sticky support to CSSLint

- .eslintrc
- background/background.js
- background/style-via-api.js
- content/apply.js
- manifest.json
Fixes #232.
XML document's page DOM is the actual XML in Firefox so we can't add style elements anywhere. This PR implements a workaround: once the content script detects `XMLDocument`, it reroutes all messages it receives to `styleViaAPI` which runs in the background context.
@fxedel, @Mottie, @narcolepticinsomniac, @eight04, please test and review the code as it's not trivial and I can't just push it in the master branch.
> FF: use tabs API for XML viewer

- edit/applies-to-line-widget.js
Reduce `$element()` calls.
BTW, the line widget is broken:
1. If document at-rules are edited in the editor, line widgets disappear.
2. If applies-to value is edited in the line widget input, the input element loses focus.
> Cache line widget template

- global.css
- options/options.css
Radio button, color inputs, and a font issue are the last details that needed fixing in Linux. I made some plain old CSS radio buttons and gave them a little personality with a quick transitioned scale on the dot. They look pretty much exactly like a cross between Windows FF and Chromium radio buttons. FF has darker ones, Chromium has lighter ones, theses are in-between.
I think they're fine to use as the default in all browsers. We only have the one radio button in options anyway. If you guys hate them for whatever reason, we can tweak them, or only use them for Linux FF, because that's where they're really necessary.
Also fixed the font issue described [here](https://github.com/openstyles/stylus/pull/291#issuecomment-350298504) and the color inputs.
> Custom radio buttons and the last few Linux details

- _locales/en/messages.json
- options.html
- options/options.css
- options/options.js
* Moved the note about importing from Stylish to the option's tooltip shown over the text and the number input.
Now it's more discoverable compared to the gray small text in the footer. The only downside is that Android users won't see it, but that's an edge case which we'll handle later when we make our mobile UI more accessible.
* Moved the actually important text about 0 disabling the updates into the option text.
* Rephrased to avoid TL;DR
@narcolepticinsomniac, any objections/suggestions?
> simplify the options page

- popup.html
- popup/hotkeys.js
- popup/popup.css
Moving `#hotkey-info` inside of `#installed` still makes the most sense to me. With a few adjustments to the CSS, we can lose the js calc for its height altogether. I also don't see a reason for it to be the entire height of the popup if the popup is already tall enough to accommodate it, so I adjusted that as well. I don't think a wrapper would be a huge deal, but I don't see a need for one anyway.
I suppose there may be scenarios I'm not accounting for, but everything appears to look right and work correctly with these changes. Goes without saying, whenever I modify js it should be scrutinized. In this case I wouldn't be surprised if I left some code made irrelevant by what I removed.
> Popup overflow

- _locales/en/messages.json
- manage.html
- manage/manage.css
- manifest.json
* `https` in manifest.json's homepage URL
* `Get styles` instead of `Get styles on userstyles.org`
* `Get help` points to https://add0n.com/stylus.html#features to skip the annoying ad
* `Wiki` points to https://github.com/openstyles/stylus/wiki
* All three labels are separate plain-text messages so now we have one html message left, we'll deal with that later
> add a wiki link, shorten the USO link, use https everywhere

- README.md
Preview link: https://github.com/openstyles/stylus/tree/readme
/me hijacked this issue to host the screenshots for readme.md
> Add highlights and screenshots sections to readme

- _locales/en/messages.json
- js/usercss.js
- manage/config-dialog.css
- manage/config-dialog.js
Adds new usercss variables & behavior:
* Add number & range variables:
* `@var number some-number "Number" [10, 0, 20, 1, "px"]` (`[default, min, max, step, units]`).
* `@var range  some-range  "Range (0-10)"  [5, 0, 10, 1, "em"]` (`[default, min, max, step, units]`)
* The `min`, `max`, `step` and `units` are optional; but added sequentially.
* Focusing on a text input will select all content.
* Default select option is set by including a `*` at the end of the key, e.g.
* `@var select aSelect "Font"   ["Arial", "Consolas*", "Times New Roman"]`
* ```
@var select aSelect "Font" {
"Arial": "arial",
"Consolas*": "consolas",
"Times": "Times New Roman"
}
```
------
Example UserCSS:
```css
/* ==UserStyle==
@namespace      stylus#492
@name           new variables
@version        1.0.0 …
```
> Add number & range Usercss variables (#492)

- background/db.js
Fixes #546 
It saves the validation error so we can inspect it with
```js
chromeLocal.getValue('dbInChromeStorageReason')
```
However, I don't know how to test this branch. Is there a way to make indexed DB fail manually?
> Add: store the reason why db failed

- background/update.js
- content/install-hook-userstyles.js
- popup/search-results.js
I'm not sure if this is a good fix...
It looks like USO fixed the md5Url `update.update` link (see #527), but now the JSON `originalMd5` doesn't always match the md5 in the md5-url:
* _GitHub-Dark_
* [JSON `originalMd5`](https://userstyles.org/styles/chrome/37035.json) = `c07b885446fb71e6af18922aa58a5f3b`
* [md5-url](https://update.userstyles.org/37035.md5) = `26c2370c297f99f8e5334c840e4b9e26`
* _GitHub-Fixed-Header_
* [JSON `originalMd5`](https://userstyles.org/styles/chrome/124438.json) = `5a532095352f9e85cccf48b0b65268ac`
* [md5-url](https://update.userstyles.org/124438.md5) = `5a532095352f9e85cccf48b0b65268ac`
> Fix USO update button

- vendor-overwrites/colorpicker/colorconverter.js
I've only tested this in the UserCSS metadata, I think the CSSLint parser covers validation of the colors in the main css portion.
> Validate UserCSS meta colors. Fixes #554

- manage/updater-ui.js
I have a bunch of DeepDark styles installed and I noticed there's an extra double quote at the end of the variable:
@var color custom-main-color "Custom main color" #00adee"
It was ignored before, but since we added color validation it throws an error and prevents updating the style. The error reported is `[object Object]`
This PR fixes the tooltip to show the correct message:
Is this work-around sufficient? Or do we need to have the metadata parser pass a string instead of an error object?
Note: I open an issue for [DuckDuckGo-DeepDark](https://gitlab.com/RaitaroH/DuckDuckGo-DeepDark/issues/1) but didn't bother with the other styles since they all have the same error.
> Show error in tooltip

- _locales/en/messages.json
- background/background.js
- sync/import-export-dropbox.js
Don't allow connection to Dropbox in dev mode; show this message in the modal instead of "Connecting Dropbox...":
> Show Dropbox unavailable in dev mode

- edit/codemirror-default.js
- edit/sections-editor.js
Fixes #563.
The logic is wrong so it should be broken on all browsers. @Mottie are you sure that it works on FF63?
> Fix: cycle through editors

- _locales/en/messages.json
- popup.html
- popup/popup.js
1. Stop including the "Stylus can access file:// URLs only if you enable the corresponding checkbox for Stylus extension on chrome://extensions page." message in Firefox.
2. Add "Stylus can not access all locally loaded file types (e.g. pdf & json files)." for inaccessible files.
> Fix inaccessible file message. Closes #574

- vendor-overwrites/csslint/parserlib.js
Fixes #579.
Didn't test it a lot on other styles.
> specify the end token for simple block in _expr()

- popup/search-results.js
For some unknown reason, USO now requires a new param.
> Fix inline search

- edit/codemirror-default.css
- edit/edit.css
- edit/global-search.css
- edit/global-search.js
Regular highlight styling and search highlight styling shouldn't both be applied at the same time. Search highlight styling should also be removed when search is closed. This PR resolves those conflicts.
> Fix search highlight conflict

- background/background.js
- background/content-scripts.js
- manifest.json
I was trying to reinject content scripts in FF (#621) but it doesn't work. This PR split out the injection logic to `content-scripts.js`.
> Refactor: pull out content-scripts.js

- vendor-overwrites/colorpicker/colorview.js
Fixes the case when a color wasn't detected if the previous line also had a color and ended with an inline comment.
```css
a {
color: hsla(240, 100%, 50%, .05); /* comment */
color: hsla(240, 100%, 50%, .4);
}
```
> fix colorview detection with inline comments

- install-usercss/install-usercss.js
- js/usercss.js
Fixes #650.
This PR allows usercss to set `@updateURL` for all cases, even if the style is installed from an available source. For example, if you install Github Dark from `https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/github-dark.user.css`, the update URL becomes `https://stylishthemes.github.io/GitHub-Dark/github-dark.user.css` in this PR.
Style hoster can also use this method to trigger a redirect, which doesn't require users to re-install the style to overwrite the updateURL.
If `@updateURL` is not defined in usercss, installation URL is used like before.
> Add: enable usercss updateURL

- edit/codemirror-default.js
- vendor-overwrites/csslint/csslint.js
- vendor-overwrites/csslint/parserlib.js
I didn't test the performance impact of adding `env()` so hopefully someone tests it here.
* fixed embedded overrides broken long time ago:
```js
/* csslint ignore:start */
"the chunk of code where errors won't be reported"
"the chunk's start is hardwired to the of the opening comment"
"the chunk's end is hardwired to the line of the closing comment"
/* csslint ignore:end */
```
```js
/* csslint allow:rulename1,rulename2,... */
"allows to break the specified rules on a single line of code that follows the comment"
```  
```js
/* csslint rulename1 */
/* csslint rulename2:N */
/* csslint rulename3:N, rulename4:N */
"entire code is affected;"
"comments futher down the code extend/override previous comments of this kind"
```
`N` can be one of the following:
* `2` or `true` means "error"
* `1` …
> CSSLint and parserlib

- background/background.js
See https://github.com/openstyles/stylus/issues/618#issuecomment-449589223
* This PR allows Firefox to install UserCSS files from any CSP restricted sites (including GitHub & Dropbox).
* Switched to using `pathSuffix` due to urls with a search query not being ignored with `urlSuffix`.
* Did not extensively test to see if this change slowed down browsing.
> Firefox allow CSP UserCSS install from anywhere. See #618

- js/dom.js
I think the combo of  swapping `window.prefs` for `prefs`, and moving the function inside `onDOMready()` does the trick. 
@eight04 Any idea why `window.prefs` no longer works? Does the rest LGTY?
> Fix missing FF favicons Closes #683

- manage/config-dialog.js
- msgbox/msgbox.css
Noticed unnecessary overflow in Github Dark's config dialog. We should allow it to utilize available height.
> Improve height restriction for popup config dialog

- edit/edit.css
- edit/refresh-on-view.js
- edit/sections-editor-section.js
- edit/sections-editor.js
Fixes #722.
1. Try to fit each editor to its content.
2. If the section is larger than the window, shrink the editor so the section can fit the window.
3. After every editor is loaded and there is an available space, stretch each editor with `availableSpace / sections.length`.
> Add: auto resize editors on init in section editor

- vendor-overwrites/colorpicker/colorconverter.js
- vendor-overwrites/colorpicker/colorview.js
fixes #744 and restores scientific number notation support in colors like `rgba(1.5E2 0 0 / .5e2%)` broken in 7ea0200
> Fix colorpicker

- edit.html
- edit/edit.css
- edit/edit.js
- edit/linter-report.js
- js/dom.js
Closes #748
While investigating the best way to fix linter scrolling, when I double-checked the compact layout, an old bug I meant to fix a long time ago was immediately apparent. Basically, the linter adds/removes errors as you type, causing the editor to bounce up and down, making it practically unusable. 
This PR fixes scrolling, and also collapses options and the linter in the compact layout, but always shows the collapsed linter so you're aware of the error count without the content jumping. It also collapses options in the non-compact layout if the viewport is too short to accommodate them, factoring in the min-height of the linter. All automatic collapsing factors in whether a linter is active so they can adjust accordingly, and disables the setting of collapsed state prefs, since …
> linter and compact layout improvements

- README.md
This pull request adds a primary header to the README for accessibility and replaces the line break tags with their markdown counterparts.
> Add primary header to README

- edit/applies-to-line-widget.js
- edit/codemirror-default.js
- js/messaging.js
Eliminates the unnecessary re-rendering of:
* Section "applies-to" widgets
* CodeMirror fold gutter marks
Alleviates #785, but not fully as there are other issues caused by CodeMirror and its addons, which someone will have to investigate separately (at the moment it seems like an architectural deficiency of CodeMirror).
I didn't test this PR extensively.
Devtools profiler in [Google Search Material Dark](https://github.com/Weikardzaena/WebsiteDarkThemes/blob/material-elevation/google-search-dark.user.css), typing inside a `@-moz-document` section:
* findAppliesTo before this PR - 2200 milliseconds
* findAppliesTo after this PR - 1.5 milliseconds
> find @-moz-doc sections faster in the editor

- popup/search-results.js
* Fixes #829, fixes #824.
It simply searches for `third.main.tld` first (if it's not org/com) or `main.tld` (if third is www or m or absent), then for `category` from the first visible result if any, then for  `main`. This may look weird as the second search results appear after a while (might be a temporary slowdown of my net or their server) but it is the solution I came up with after seeing that USO may provide different non-overlapping contents for both categories even if the styles are for the same site as evidenced by another popular ru site: `pikabu.ru` (a handful of styles) vs `pikabu` (lots of styles).
* Speeds up search for Stylus themes by querying `chrome-extension` category.
> automatic category fallback in style search

- background/db-chrome-storage.js
- background/db.js
- manifest.json
Fixes #839
* Fix: a save style error. The process failed but the data is stored in the DB.
* Fix: a race condition that may result in duplicated ID.
To test this branch, you have to switch to chrome storage DB by setting `localStorage.dbInChromeStorage` to `"true"` and reload the extension.
> Refactor chromeStorageDB

- background/background.js
Repro:
1. open a tab with a few styles applied
2. right-click the Stylus toolbar icon
3. toggle "Show active style count"
Expected: the badge is toggled
Observed: nothing happens until the tab is reloaded
Also happens when changing the option in the options dialog.
It was broken in #518, and looks like a typo: `refreshAllIcons` should be `refreshAllIconsBadgeText`.
> apply show-badge option to all tabs

- content/apply.js
- content/style-injector.js
- js/msg.js
- js/polyfill.js
- js/prefs.js
- js/promisify.js
Removes the page script, simplifies and speeds up style injection by using FF49+ wrappedJSObject to create style elements in page context, which is needed for Firefox (#461). But only if page CSP doesn't block inline styles.
Also disables the part of polyfill.js that's not used in content scripts or can't be used (like localStorage, which shouldn't be used by anything running in a worker, I hope, @eight04 ?).
P.S. Ideally all content scripts should be compiled/bundled into one script because currently the six content scripts may intertwine with site scripts (six scripts provide five opportunities for the browser to reschedule and postpone them) thus delaying style request and response. Stylus 1.4.22 was always sending the request in under 3ms after its start whereas now the six content …
> Simplify & speed up style injection

- content/style-injector.js
Closes #844.
After installing the style below the test case is as follows: 
1. open https://www.google.com/
2. switch to another tab in the same window
3. right-click the google's tab and click "reload"
4. wait a random amount of time and switch to google's tab 
Expected: no transitions on the red buttons
This is an old CSS we used to test the transition bug:
```css
/* ==UserStyle==
@name           !transition bug
@namespace      github.com/openstyles/stylus
@version        1.0.0
==/UserStyle== */
@-moz-document url-prefix("https://www.google.") {
input[type="submit"] {
-moz-appearance: none!important;
background: red!important;
transition: 1s !important;
}
input[type="submit"]:hover {
background: cyan!important;
}
}
```
> skip transition-patch in invisible tabs

- background/background.js
- js/messaging.js
* Fixes the only case when `openerTabId` can differ from the active tab: when auto-opening a usercss installer for an inactive tab. In all other cases we call openURL from a click event which obviously happens in the currently active tab.
* Removes the unused shorthand invocation mode openURL(url)
* Fixes the outdated JSDoc comment and tweaks a few trivial things, see comments in code
> fix usage of openerTabId in openURL + cosmetics

- popup/search-results.js
Example URL: https://developers.google.com/web/updates/2020/02/twa-lay-of-the-land
Currently searching for `foo.bar.com` strips `com`, tries `foo.bar`, and fails.
It will look for the entire thing now in the first try.
> fix category check when searching for `foo.bar.tld`

- background/background.js
- background/icon-manager.js
- background/style-via-api.js
- background/tab-manager.js
- content/apply.js
- js/messaging.js
- popup.html
- popup/popup.css
- popup/popup.js
Closes #191.
If the site has iframes a `[+]` toggle is shown to the left of the #write-style block.
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
* https://css-tricks.com/responsive-iframes/
* https://www.tutorialrepublic.com/html-tutorial/html-iframes.php
Styles for iframes are shown in the list and counted in the badge text.
> show write-style entries for iframes in popup

- .github/CONTRIBUTING.md
The non Capitalized link will give you the 404 page not found error.
[Wrong link Current one 		Build.md](https://github.com/openstyles/stylus/blob/master/Build.md)
[Correct link Commited one 		BUILD.md](https://github.com/openstyles/stylus/blob/master/BUILD.md)
> Contributing.md - Fix Build.md link

- manifest.json
IndexedDB storage [may be evicted by the browser at its discretion][1]. Granting the unlimitedStorage permission [ensures that IndexedDB data will not be evicted][2], and [allows the extension to store more than 5MB of data if needed][3].
This is the root cause of how my IndexedDB got "corrupted" one time, as my storage filled up temporarily - causing Stylus's IndexedDB to be evicted. FWIW, Tampermonkey (a similar manager for userscripts) uses the same permission, so it's probably safe to use for Stylus.
[1]: https://web.dev/storage-for-the-web/#eviction
[2]: https://crbug.com/680392#c5
[3]: https://developer.chrome.com/apps/declare_permissions#unlimitedStorage
> Add unlimitedStorage permission

- background/background.js
- background/icon-manager.js
- js/messaging.js
- manage/manage.js
- options/options.js
- popup/popup.js
Fixes #943, assuming Chrome will expose only the major browser version in its UA string.
Another solution/workaround that I rejected is to use feature detection based on https://www.chromestatus.com/features but it's really not that straightforward because some features were added in earlier versions of Chrome and were hidden under some flag, for example behind the "experimental web platform features" flag often enabled by people for kicks.
> use major browser version in CHROME constant

- edit/codemirror-default.css
- edit/codemirror-default.js
* Implements #949 since CodeMirror's author doesn't want to. The default style is really primitive: it's a gradient from currentColor to transparent over the line number.
* Removes the no longer needed optimization which is included in CodeMirror.
> show sublime bookmarks

- manage/manage.js
- msgbox/msgbox.css
- popup/popup.css
I did miss this point in the [OP](https://github.com/openstyles/stylus/issues/954), mostly because my personal style hides focus outlines anyway. The delete button is also focused when the manager confirmation dialog appears, but it seems like our 'focused-via-click' hack is interfering with this particular focus outline.
This PR fixes that, and makes these focus outlines red for good measure.
@tophf if you'd prefer to tweak the accessibility hack, feel free, but I'm not screwing around with it.
> Improve delete confirmation autofocus visual indication

- _locales/en/messages.json
- edit/beautify.js
- edit/colorpicker-helper.js
- edit/edit.css
- edit/edit.js
- edit/reroute-hotkeys.js
- edit/sections-editor-section.js
- edit/sections-editor.js
- edit/util.js
- js/prefs.js
Fixes #970.
Pressing a configurable hotkey or right-clicking the Beautify button will perform beautification silently i.e. without showing the dialog. This info and the hotkey input itself are shown at the bottom of the beautify panel.
> add a hotkey & right-click to beautify silently

- manage/sort.js
Previously, when sorting by updateDate the newly installed styles weren't on top, which felt wrong.
> when sorting on updateDate use installDate as a fallback

- vendor-overwrites/csslint/csslint.js
Fixes #976.
<details><summary>I guess this instruction should be added to our wiki in a more readable form.</summary>
```
/* csslint ignore:start */
/*
the chunk of code where errors won't be reported
the chunk's start is hardwired to the line of the opening comment
the chunk's end is hardwired to the line of the closing comment
*/
/* csslint ignore:end */
```
Allow rule violations on the current line:
```css
foo: bar; /* csslint allow:rulename1,rulename2,... */
/* csslint allow:rulename1,rulename2,... */ foo: bar;
```
```css
/* csslint rulename1 */
/* csslint rulename2:N */
/* csslint rulename3:N, rulename4:N */
```
* entire code is affected
* comments futher down the code extend/override previous comments of this kind
* values for N (without quotes):
* `2` or `true` means "error"
* `1` …
> use current-line mode for csslint allow override

- popup/search-results.js
Turns out USO takes ~30 seconds to connect now, which is a ridiculous amount but at least it works.
> increase USO style search timeout

- vendor-overwrites/csslint/parserlib.js
Follow-up to #981 fixing the check for `||` combinator.
> fix column combinator detection

- js/worker-util.js
This PR prolongs the linter worker lifetime from 30 seconds to 5 minutes. Both in the editor tab and in the background script. Currently, the worker restarts **a lot** when working on a style for a long time. Each restart stresses the CPU to perform code compilation/analysis, and obliterates the purpose of the parser cache in CSSLint that normally provides up to 10x speedup.
> prolong worker lifetime to 5 minutes

- edit/codemirror-default.js
Follow-up to #915 solving two problems when auto-completing inside `foo` of an existing declaration like `foo: 123`
* in case the cursor is at the end of `foo` don't insert an extraneous `: `
* in case the cursor is in the middle of `foo` and we've chosen `foo-bar` in the menu, prevent ending up with `foo-bar: oo: 123` by consuming the leftovers so it'll be simply `foo-bar: 123`
> consume leftovers when auto-completing properties

- edit/sections-editor.js
- edit/show-keymap-help.js
The bug was mentioned in #1004.
In new Chrome we should register document-level scroll listeners as non-passive explicitly.
I've also removed this hotkey from the keymap help in usercss mode because it's not registered there (no need).
> restore Shift-Ctrl-Wheel to scroll window in multi-section mode

- js/dom.js
Dummy links with `#` url that we use for action elements should not change the URL as their actions aren't navigations.
> avoid adding # to the page URL when clicking dummy links

- edit/edit.js
Unlike DOM `resize` event, this one also reports movement even if not resized.
Currently available in a) the latest chromium snapshot from https://download-chromium.appspot.com or b) Chrome Canary that's based on revision greater than 793515 per https://omahaproxy.appspot.com, which should be its next update.
> use onBoundsChanged to remember editor size/position

- background/sync.js
- package-lock.json
Correctly display sync start errors e.g. connecting to onedrive on latest Firefox:
> Fix: show sync start error

- background/background.js
- background/content-scripts.js
- background/navigator-util.js
- edit/regexp-tester.js
- js/messaging.js
- js/msg.js
Fixes #1039, arguably.
When a tab is pending navigation, the new URL is set only as [tab.pendingUrl](https://developer.chrome.com/extensions/tabs#type-Tab) since Chrome/ium 79, so we need to always check it prior to `tab.url` except when it doesn't make sense, like in FF, duh. Note that in new tabs pending navigation `tab.url` is empty `''`, which seems to be the cause of the linked bug.
> use tab.pendingUrl

- edit/codemirror-default.js
- js/moz-parser.js
- vendor-overwrites/csslint/parserlib.js
Turns out `*` in `*color: red` is a [IE hack](https://stackoverflow.com/a/1690683/) so it's used in the wild. Our linter already has starHack enabled and processes (ignores) `*` successfully. Now, this PR enables the same for the parser.
Fixes #1035.
> parser: enable starHack option + new props

- _locales/bg/messages.json
- _locales/cs/messages.json
- _locales/de/messages.json
- _locales/en/messages.json
- _locales/es/messages.json
- _locales/et/messages.json
- _locales/fr/messages.json
- _locales/he/messages.json
- _locales/hu/messages.json
- _locales/it/messages.json
- _locales/ja/messages.json
- _locales/ko/messages.json
- _locales/nl/messages.json
- _locales/pl/messages.json
- _locales/pt_PT/messages.json
- _locales/ro/messages.json
- _locales/ru/messages.json
- _locales/sv/messages.json
- _locales/tr/messages.json
- _locales/zh_CN/messages.json
- _locales/zh_TW/messages.json
- js/prefs.js
- manage.html
- manage/manage.css
- manage/manage.js
- options.html
- options/options.js
Moves the 1) newUI options block and 2) theme button from the manager into the options page which we/I wanted to do since forever once we made a dedicated options page. The shortcuts button is already present in the options page.
Now that the theme option is in the options page, it should increase its discoverability which was kinda low due to the dense and cluttered nav panel in manage.html.
> rework and move newUI+theme to options.html

- background/style-manager.js
Fixes #735.
Sections with an empty `url-prefix` won't become global now.
Quoting myself:
> Theoretically it might break a couple of styles where clueless authors added a useless `@-moz-document url-prefix("")` but I think we can ignore that as it's totally nonsensical. If someone wanted to "organize" the code that way they could simply use `@-moz-document { ............ }` without `url-prefix`.
> treat empty url-prefix() as non-matching

- background/content-scripts.js
- content/install-hook-greasyfork.js
Fixes #842.
Uses messaging via `window`.
The content script is injected dynamically because AFAIK browsers still retardedly disable the extension on update when a content script is added in manifest.json even though it does not actually extend the previous span of host access, which is already `<all_urls>`.
> expose version for styles installed from greasyfork/sleazyfork

- background/background-worker.js
- js/moz-parser.js
- js/usercss.js
- vendor-overwrites/csslint/parserlib.js
fixes #477 since we still couldn't find a way to build the updated stylus-lang into a small bundle ourselves.
> ignore empty documents produced by stylus-lang bug

- _locales/en/messages.json
- background/background.js
- js/messaging.js
- js/prefs.js
- manage/manage.js
- options.html
Adds an option to use a simple window (no omnibox) when opening editor in a new window.
The option is not enabled by default in order not to aggravate the users. FWIW personally I like this simplified window better as there are no distractions and it provides more space for the code.
> option to open editor in a simple window (no omnibox)

- options.html
- options/options.css
- options/options.js
* Move overflow, so actions block is never hidden.
* Fix missing favicon info message box text.
* Make link and icon styling consistent with the rest of the UI.
* Indicate clickable areas better.
The latter may be debatable. Pointer cursors on labels aren't exactly standard, so I won't argue much if there's any disagreement. What we had already was just weird though, probably done by me at some point, in my infinite wisdom.
Previously, we had cursor pointers on label span, which defeats the actual purpose of indicating that the entire label, and everything in it, is one clickable area with the same action. I don't think some subtle text shadow, with a default cursor, is a clear enough indication.
Given the fact that labels are too compact for background styling not to look odd, styling …
> Options tweaks

- _locales/en/messages.json
- background/usercss-helper.js
- edit/sections-editor-section.js
- edit/sections-editor.js
- msgbox/msgbox.css
- msgbox/msgbox.js
Fixes #1080 by showing a warning when a non-empty `@preprocessor` is detected inside a valid usercss metadata comment. Didn't implement automatic switching to usercss mode because it's not trivial and this scenario is too rare to invest the effort.
> warn when paste-importing usercss with @preprocessor

- background/background.js
- content/apply.js
- js/msg.js
Fixes #906.
There should be no functional changes but let's test this for a while anyway.
Code-wise, since conversion to async/await changes the code a lot, I also shuffled and reworked the entire msg.js mainly to reduce indirection i.e. to make call chains shorter hence more obvious while debugging or navigating through the code especially when using "jump to definition" and "peek definition".
> async'ify msg, don't throw for flow control

- _locales/en/messages.json
- edit/colorpicker-helper.js
- js/prefs.js
- manage/config-dialog.js
- vendor-overwrites/colorpicker/colorpicker.css
- vendor-overwrites/colorpicker/colorpicker.js
- vendor-overwrites/colorpicker/colorview.js
Fixes #1071.
Turns out the autohide feature was a legacy of the original code. No other apps have it AFAIK and it's pretty annoying to keep the mouse over the dialog to prevent it from closing so I've removed the option.
Increased the size of the big swatch on the left to make its margins more even. Kind of.
Added a grip area on the right to move the dialog. I'm not a UI designer but it's probably recognizable, moreover the cursor is changing which should make the function pretty much self-explanatory.
> tweak colorpicker

- .github/workflows/ci.yml
Only run on a single node version, that way you won't get triple error annotations, and it's really not neccessary for this repo to test on multiples anyways.
> Simplify CI action

- _locales/en/messages.json
- js/prefs.js
- manage.html
- manage/config-dialog.css
- manage/manage.css
- manage/manage.js
- options.html
- options/onoffswitch.css
- popup.html
- popup/hotkeys.js
- popup/popup.css
- popup/popup.js
Showing `usercss` was probably warranted at the beginning to introduce the feature but now it's just wasting space and attention so let's reduce it to just `U`:
> reduce usercss bubble to `U`

- manage/manage.css
- manage/manage.js
- options/onoffswitch.css
- popup/popup.css
- popup/popup.js
Fixes https://github.com/openstyles/stylus/pull/1117#issuecomment-731560300
> Disabled popup entry contents should not be opaque.
Changing opacity on the name would also apply it to the inner checkbox/slider, which is wrong. We could of course change the html but remembering how you dislike opacity on text I went with `color: #999`.
> * 7px looks fine
> * styling sliders on .style-name:hover
> * Removing pointer-events
> * iframe' indicator shouldn't interfere
> * restricted message, while still listing active iframe styles
Done.
> tweaks and fixes

- _locales/en/messages.json
- js/dom.js
- popup.html
- popup/popup-preinit.js
- popup/popup.css
- popup/popup.js
- popup/search-results.css
- popup/search-results.js
There's a problem in Chrome: as usual it tries to be fast and paints an empty popup for a fraction of a second, then the data arrives and the popup is resized to accommodate it, which looks fussy and unpleasant. This PR fixes the problem by getting the data earlier.
Nothing I can do to fix the micro-sized popup (like 40x40 px) that Chrome paints occasionally, really rarely.
> faster popup load to avoid resize flicker

- edit/edit.css
- edit/edit.js
- js/dom.js
There's a problem with our otherwise cool `simple window` option: browsers can't show the browser_action popup neither via a click nor a hotkey.
This PR adds such a button in the top-right corner and a hotkey: <kbd>Shift</kbd><kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>S</kbd>.
The button looks bad in usercss non-compact mode though so maybe you could find/suggest an acceptable solution @narcolepticinsomniac ? For today, I'm off to sleep.
> [simple-window editor] embed popup as iframe

- edit/codemirror-default.css
- edit/codemirror-default.js
- edit/codemirror-factory.js
- edit/colorpicker-helper.js
- edit/edit.css
- edit/sections-editor.js
- edit/source-editor.js
- vendor-overwrites/colorpicker/colorview.js
Fixes #952.
Line number area accepts mouse clicks now:
* <kbd>Left button</kbd> toggles bookmark
* <kbd>Right button</kbd> goes to the next bookmark (or previous if <kbd>Ctrl</kbd> is held)
* <kbd>Middle button</kbd> selects all bookmarked positions, useful when multi-editing
Changed the default style so it's more noticeable especially in the dark themes:
As for cycling through all sections, that's not reliably possible with the way sublime bookmarks work as their next/previous order isn't based on a line number but rather on the bookmarking order so it may jump all around the place within one section. This implementation seems weird but I'm not sure we can convince CodeMirror's author so maybe I could just re-implement bookmarking myself one day. That would make it available for all …
> improve bookmarking

- edit/codemirror-default.js
- edit/codemirror-factory.js
- vendor-overwrites/colorpicker/colorview.js
* correctly handle search overlay if it covers some part of the token
* correctly show props with `@preprocessor stylus`
* show `@` rules and `@-moz-document` functions and some missing filters
So, rather trivial changes but I'm opening a PR anyway for testing because I've rewritten the entire function.
> improve autocomplete

- background/navigation-manager.js
- background/style-manager.js
- background/style-search-db.js
- background/update-manager.js
- background/usercss-install-helper.js
- background/usercss-manager.js
- edit/sections-editor.js
- edit/source-editor.js
- js/toolbox.js
- js/usercss-compiler.js
- manage/import-export.js
- manage/manage.css
- manage/render.js
- popup/search.js
There will be no additional prompts or tooltips shown for this process.
The advanced settings of the style are preserved.
Also fixes #1122 - the author of the style should update it on USO site first, then Stylus will use the embedded UserCSS metadata during the next update check.
> convert USO styles to USO-archive on update

- _locales/en/messages.json
- background/icon-manager.js
- background/sync-manager.js
- background/tab-manager.js
- package-lock.json
Fixes #800.
It shows `x` in a red-colored icon badge when any sync error occurs with a tooltip `Sync failed. Please re-login.`
Maybe I should limit it to certain errors, @eight04 do you know which ones?
> indicate sync error as 'x' in icon badge

- edit/edit.css
- edit/linter-dialogs.js
Some trivial tweaks in the popup that opens when clicking `(i)` next to `Issues` heading to alleviate #1170:
* show rule id so the user can configure it
* add "configure" button to show the linter config UI
* add margins between items
* emphasize active rules
> improve linter info and config popup

- edit.html
- edit/edit.css
- edit/moz-section-widget.js
- edit/regexp-tester.js
- global.css
- js/dlg/config-dialog.js
- js/dom.js
- manage.html
- manage/updater-ui.js
- options.html
- popup.html
- popup/events.js
- popup/popup.js
The reason is that dummy links like `<a href="#">` cause the built-in browser tooltip pop up on hover with chrome-extension:// URL - in addition to the intentional tooltip - which is just useless noise.
Functionally there should be no difference assuming I found all the places where dummy links were used.
Theoretically it may break parts of some themes that specified the tag instead of the class name, but that's bad practice AFAIK. The most popular themes seem to be fine though.
> switch from dummy links to dummy buttons

- edit.html
- global.css
- js/dom.js
- manage.html
- options.html
- popup.html
This PR extends our existing Firefox workaround to Chrome and deduplicates it into one place in global.css.
I've been observing the transition bug when opening the style manager page in Chrome for several months until I realized what it was and remembered we can hide it. Previously the bug wasn't visible probably because our pages loaded a bit slower or I just didn't pay attention.
> suppress transition bug on page open in Chrome, too

- background/style-manager.js
- js/color/color-converter.js
- js/usercss-compiler.js
- manage/import-export.js
~Disables opacity in the config dialog for styles with `@preprocessor uso` as it's not supported to match the original site's behavior.~
Did a U-turn, see the investigation in comments below, now it's the opposite:
USO has always produced 6-digit #rrggbb so some styles rely on it
and use `/*[[color]]*/11` notation to specify the transparency.
Now we will try to preserve the opacity customized by the user
via colorpicker unless the style specifies it inline.
Fixes #1199.
> preserve opacity in colorpicker for preprocessor uso config

- js/localization.js
- manage/events.js
The time is always shown.
The day of week is shown for intervals within the past seven days.
Any objections/suggestions?
> show time/weekday in tooltip for style entries

- content/install-hook-usercss.js
- install-usercss/preinit.js
Following discussion in #1176 I've used `git bisect` to find the first failing commit as @tophf suggested. Starting from last good version `v1.5.13` reported by @vednoc I've arrived at commit 707cd6576f2d930211be50f21362027b6cb9e873 as the first bad commit.
From what I was able to get reading the code and reproducing the error state shown on [screenshot from original report](https://user-images.githubusercontent.com/18245694/107519428-8da8d400-6bb0-11eb-8df0-740161ec7c88.png), it looks like the error comes from changing the logic in `downloadSelf` event listener.
Old code used this condition for determining when to fill in `code` value of the msg passed:
```
.then(code => ({id, code: timer && code === self.oldCode ? null : code}))
```
while new logic uses something like this (note the use …
> Fix #1176 Installing local UserCSS style fails in Firefox

- background/icon-manager.js
Currently the offscreencanvas is being used for '2d' context, however Firefox(when enabled in `about:config` `gfx.offscreencanvas.enabled`) doesn't implement this as for now, see: https://searchfox.org/mozilla-central/source/dom/canvas/OffscreenCanvas.cpp#105-110 and it will error out multiple times within the console.
> Disable Offscreencanvas for firefox

- background/style-manager.js
- content/install-hook-userstylesworld.js
- Don't use sourceCode as "temporary" value as it's being used as legit value(consider that we delete it after it's non longer needed).
- Wrap the metadata into a `try {}` as some styles doesn't have any metadata.
Thanks @narcolepticinsomniac for testing it out first.
> Fix integration

- background/style-manager.js
- background/token-manager.js
- Resolves #1276
- Just pass the parameter which is either undefined or an number. No need to get it from a object, while we can just pass the property already.
> Passing `object` -> Passing `property`

- background/style-manager.js
- edit/edit.js
As we somehow forgot to add some basic metadata checks to the server, we've now enabled it and added some more errors. In such situations the errors should been shown to the user to understand what's happening.
Related USw commit: https://github.com/userstyles-world/userstyles.world/commit/7c6d2c519b4021c409721d909741c0e4bac0c334
Also I've noticed that messageBox.show() doesn't handle `\n`?
@vednoc FYI
> Show error to user when USw returns error

- background/style-via-webrequest.js
Hopefully, it's an acceptable way to fix (even if partially) #1296.
> patchCSP option: allow `@import` from any URL

- content/install-hook-userstylesworld.js
Add the "architecture" for style-request which currently only is "installed" but and probably will expand in the future. 
The "installed" message is now used to add the "Write a review" button and to change the "Install" button's text to "Reinstall".
Related USw commit: https://github.com/userstyles-world/userstyles.world/commit/2d3b0e0281508e44b0d7ca74dbd42e7c08ee6d6c
@FreeplayG - this is 1 of the pieces for the "Write a review" suggestion you had.  So follow the PR if you'd like.
Topfh - As I can't really bother by giving myself a hard time naming variable, I just chose a generic name and gave a little more specific "type" to describe what USw is requesting. Also this is something we don't request in pair of `usw-ready` as this one is only requesting when the user is on the a style's …
> Send requested info

- content/install-hook-userstylesworld.js
* extract handlers to async functions
* limit event source to the current window
* the event's origin is not checked because this content script runs only on allowed origins
@Gusted, please check if I missed or borked something. I'm opening this PR since my suggestion to use `switch` didn't seem to be an improvement so this time I've used a map of handlers just like we do in our `API`.
> refactor usw content script

- background/update-manager.js
- background/usercss-install-helper.js
- js/toolbox.js
- manage/render.js
- popup/search.js
@33kk, could you please take a look at this PR as we want to use your new USO-archive URLs (including CDN) to avoid a couple of minor issues: flashing of the old address during redirection and flashing of style text when installing from the site page.
Questions:
1. I have to prefetch a big style json when the author label is clicked to get its id. This can be solved by a) adding `ai` to the index but it's rarely used so I'm not keen on this idea, b) adding a search mode `browse/styles/?author-for=${styleId}` so your site's page will download the json, extract the author id, and show the results, c) split your json to ###.meta.json without CSS and ###.css with just the css and no usercss header, by the way who uses this css in json?
2. Do you plan to change the USO-archive URLs anytime …
> update USO-archive urls

- background/icon-manager.js
- Resolves #1287
- Fenix currently doesn't seems to correctly use custom ImageData as icon. Thus disabling that feature for now is a plausible workaround.
> Fix Firefox's android icon

- js/dom.js
- popup.html
- popup/search.css
- popup/search.js
* show action hints for results that don't have a preview image
* pure CSS to control visibility of action buttons instead of hardcoded calls to show()/hide().
To see it in action, invoke the inline search on any github page. In the default sort order by updated date you'll see many such styles right away, all from USW so maybe @Gusted could investigate why USW's index contains non-existent preview urls.
> show action hints on preview-less search results

- js/meta-parser.js
Previously, resetting a color in usercss config dialog would always use `rgb` format.
This PR uses the original color format e.g. hex, rgb, hsla.
@eight04, since it was your commit 3daff40acfcb3cf07ea979dbe9e689256b9b764f, do you remember why? Will something break if the default color is not rgb? AFAICT, there's no problem because we use colorConverter to render the final value.
The change will be applied only when this style is updated/edited.
> keep the original color format in usercss @var

- edit/linter-manager.js
- js/csslint/csslint.js
- js/csslint/parserlib.js
@narcolepticinsomniac, WDYT? Should this rule also check vendor-prefixed pseudos like `::-webkit-scrollbar`?
> csslint: add "known-pseudos" rule enabled by default

- _locales/en/messages.json
- background/style-manager.js
- edit.html
- edit/base.js
- edit/edit.css
- edit/edit.js
- edit/sections-editor.js
- edit/settings.css
- edit/settings.js
- edit/source-editor.js
- edit/tab.css
- edit/tab.js
- js/event-emitter.js
Fixes #827.
There are some features linked to #827 are closed without implementation. Do you want to create a new meta thread to track them or I will just re-open the old ones?
User inclusion doesn't work either.
> Add: style settings

- js/msg.js
- js/polyfill.js
Testing in devtools console:
* `API` callstack: `await API.styles.delete(1e9)` in the style manager.
* `msg.send` callstack: `await API.styles.delete(1e9)` in any web site after choosing Stylus context in the console toolbar.
* `browser` callstack: `await browser.tabs.get(1e9)` in the style manager.
@eight04, WDYT?
> add a callstack to errors in `browser`, `API`, `msg`

- _locales/en/messages.json
- background/background.js
- background/db-chrome-storage.js
- background/db.js
- background/style-manager.js
- edit/base.js
- edit/drafts.js
- edit/edit.js
- edit/sections-editor.js
- edit/source-editor.js
- js/dlg/message-box.js
- js/dom-on-load.js
- js/prefs.js
- js/toolbox.js
- options/options.js
- popup/popup.js
Fixes #1303.
Unsaved changes in the editor are stored as a draft for this style id.
Saving removes the draft.
Opening the editor for this style will show a prompt:
The timer is `10` seconds, customizable in devtools console: `prefs.set('editor.autosaveDelay', 1)`.
Didn't add it in UI because there's a lot of settings already so I thought I'll implement CodeMirror-related stuff first (#1083).
> autosave in editor

- edit.html
- edit/edit.css
- edit/sections-editor-section.js
- edit/sections-editor.js
- edit/settings.css
- global.css
- js/dlg/config-dialog.css
* hid the `Applies-to` label and shifted (i) left, didn't change html to allow people to unhide it
* fixed select's height, it was smaller by 2px
* fixed up/down icons to show as triangles correctly
* removed the accidental margin on the right of the applies-to block
> align 'Applies-to' and actions

- background/token-manager.js
Fixes #1391.
> I don't see Stylus in MS Store so Edge probably uses a random id for such extensions intentionally. Meaning that it's probably useless to add it to Google's console. Instead we should hardcode the id ourselves (same id for the beta I guess).
> use hardcoded redirect_uri fallback

- _locales/en/messages.json
- background/style-manager.js
- background/style-via-webrequest.js
- content/apply.js
- content/style-injector.js
- js/prefs.js
- options.html
- options/options.css
This is only for Chrome because FF's devtools doesn't support sourceURL comment in style elements.
Previously, clicking the `<style>` link in the Styles inspector would select this element in the DOM tree, which was inconvenient and almost useless.
Now, when the `expose style name` option is enabled, the actual style name is shown:
Clicking this link focuses this rule in the devtools source editor:
The option is disabled by default because names can be used for tracking/fingerprinting, arguably.
We can also right-click the devtools editor tab and pick `Open in new tab` to open this style in our editor:
> expose style name

- edit.html
- edit/base.js
- edit/edit.css
- edit/edit.js
- edit/embedded-popup.js
- edit/global-search.js
- edit/linter-manager.js
- edit/moz-section-widget.js
- edit/sections-editor.js
- edit/util.js
- global.css
- js/dom.js
- manage/manage.js
- manage/sorter.js
- manifest.json
- popup/popup.js
Solves a long-standing problem with styles that have many sections so the list pushes the lint report out of view. It was also inconvenient that the header was scrollable so the Save button became invisible, and the scrollbar was awkwardly positioned to the right of the resizer grip.
Now only the details are scrollable. Their scrollbars touch the grip which looks kinda neat, although I doubt if it's ok when there's no scrollbar and the contents touches the grip e.g. in the lint report?
~I've switched to `position: sticky`, which allowed to simplify JS listeners and CSS. It's implemented in Chrome 56, so I've bumped our minimum_chrome_version, previously 55.~ One day we may even get rid of this explicit `compact-mode` class toggling and just use `@media` queries.
The sticky headers in …
> scrollable details + sticky header

- _locales/en/messages.json
- edit/edit.css
- global.css
- js/localization.js
- options.html
- options/options-sync.js
- options/options.css
- options/options.js
* removed `update styles` button, redundant now as we always show the options inside the manager; in the case someone convincingly complains we can add this no-confirmations mode to the main update button as a split button.
* moved updates and sync to the top because these are likely to be used more frequently than changing the UI whistles
* moved theme to the bottom and replaced the link with a text explaining how to use the popup search, which is better as it pulls from two repositories
* sync buttons are hidden if no provider is selected
* sync connect/disconnect button is single now, only its label changes, like a power switch
* replaced 'Back to manage' with 'Close'
* added a note for the built-in shortcuts UI in FF
> shuffle and tidy up options

- global.css
- install-usercss/install-usercss.css
- manage/updater-ui.js
- popup.html
- popup/popup.css
- popup/popup.js
While fixing the red hover on disableAll element, I got underwhelmed by the amount of CSS/HTML we had just for this hover effect, which would double up for the dark theme, so I removed these hovers, now the red color is shown statically when the checkbox is checked.
Also flattened the actions block by removing the `main-controls` kludge we had from Stylish times.
> simplify css/html in popup

- background/background.js
- background/style-manager.js
- background/update-manager.js
- background/usercss-manager.js
- background/uso-api.js
- content/install-hook-userstyles.js
- manage/render.js
- manifest.json
- popup/search.js
Fixes #1422.
When installing the style on USO it will be installed in usercss mode using the original author's CSS. The benefit of usercss mode is that the user doesn't have to visit USO to configure the style. One convenience I managed to add is that when customizing an already installed style on their site the change is applied instantly.
Since USO has been working reliably I've removed automatic redirection of styles to USO-archive so they will keep updating from USO but in usercss mode.
Conversion algorithm matches USO-archive for uniformity.
The inline search in the popup still doesn't search USO. I'd like to avoid re-adding it.
> fix USO site installation

- options/options.css
Remove the white border in stylus options from the color inputs
> Remove white border for color input

- global-dark.css
- options/options.css
Dark arrows for input numbers in Firefox when using dark mode
> Dark arrows for input number in Firefox

- background/style-manager.js
- content/install-hook-userstyles.js
- manifest.json
Fixes #1422.
I've also removed patching of the site when viewing a previously installed style i.e. the customization area will be showing now the default state just like it does with their own extension. Such patching is fragile and breaks every time the site is changed, moreover the upcoming redesign doesn't have these customizations at all. Our extension provides a much more convenient method anyway: the config dialog right inside the popup when viewing the applicable site.
@narcolepticinsomniac, WDYT?
> fix USO site install for new design

- edit/edit.css
sets the codemirror editor min-height to 20px, as someway, somehow it can end up with a height of `1px`, making it essentially completely invisible
shouldn't break codemirror resizing - it seems to have a fixed minimum of 21px
> prevent CodeMirror from disappearing by setting a min-height (#1624)

- edit/edit.css
codemirror.css line 69 contains:
.cm-fat-cursor { caret-color: transparent; }
This, however, makes the cursor invisible in the `.applies-to` widget. Oops! This commit here fixes that bug.
How to reproduce: set the keymap to "Vim", which should make the editor cursor fat.
> Fix: making the cursor visible when editing "applies-to"

- popup/popup.js
**Summary:**
This PR refactors the JavaScript logic responsible for adjusting the height of the `#stylus-popup` element within the configuration dialog. The changes align the code style with existing patterns in the project, enhance performance, and ensure maintainability.
**Key Changes:**
1. **Refactor to Match Existing Code Style:**
- Replaced direct `addEventListener` usage with the more concise `document.on` method, in line with the existing codebase.
- Utilized `$` as a shorthand for `document.querySelector` for consistent element selection.
2. **Performance Enhancements:**
- Implemented a slight delay (`setTimeout` with 25ms) to ensure that necessary DOM elements are fully available before manipulation.
- Optimized the calculation of the maximum height for the configuration dialog …
> Fix Stylus configure dialog height by refactoring and Optimizing Stylus Popup Height Adjustment Logic

- package.json
- pnpm-lock.yaml
- tools/chrome-api-no-cb.js
Was looking through the package.json, noticed node-fetch. The package.json specifies `engines.node` to be `>=20.6.0`, which only includes Node versions supporting the native `fetch` implementation.
> remove node-fetch devdep
