edit.html
manage.html
popup.css
popup.html

Switched info to `i` and found a pretty nice external link icon imo. @tophf As for pixelation on the info icons, you mentioned maybe a lighter color would help. For all icons besides external links, I made them lighter with darker hovers. Besides a really high zoom, I never saw any issue to begin with, but let me know if they're alright. I also changed them to use their exact original dimensions, so maybe that helps.

Switch info/external style link icons from img to svg

---

.github/ISSUE_TEMPLATE.md

I totally forgot to update the issue template when I copied it over from another repo!

Correct wording in issue template

---

popup/popup.css

popup: don’t assume the browser styles text in black

---

.eslintignore
_locales/en/messages.json
edit.html
edit/edit.js
js/prefs.js
vendor-overwrites/colorpicker/LICENSE
vendor-overwrites/colorpicker/colorpicker.css
vendor-overwrites/colorpicker/colorpicker.js
vendor-overwrites/colorpicker/colorview.js

Fixes #210
(assuming we don't want a separate colorpicker button under code editors)
Please test: [zip](https://github.com/openstyles/stylus/archive/colorpicker.zip).

Colorpicker

---

_locales/en/messages.json
install-usercss.html
install-usercss/install-usercss.css
install-usercss/install-usercss.js

Added color & Stylus icon to the usercss install button - ref: https://github.com/openstyles/stylus/commit/e90de3783a36e782324663397680b917f3168749

Install usercss

---

edit.html
edit/beautify.js
edit/edit.css
edit/edit.js
global.css
install-usercss.html
install-usercss/install-usercss.css
js/dom.js
js/messaging.js
manage.html
manage/config-dialog.js
manage/manage.css
msgbox/msgbox.css
popup.html
popup/popup.css
vendor-overwrites/colorpicker/colorpicker.js

Give me a minute to upload everything.

Custom checkbox and select elements

---

js/prefs.js
manage.html
manage/filters.js
manage/manage.css

| All Open | All Collapsed |
|-|-|
|  ![](https://user-images.githubusercontent.com/136959/33625408-1743e666-d9bd-11e7-9563-4016e0c13987.png) | ![](https://user-images.githubusercontent.com/136959/33625413-1b6d8c10-d9bd-11e7-8968-21be0261e372.png) |

Make filter & backup containers collapsible

---

manage/manage.js

It's rudimentary, but the code matches a bunch of RegExp's for styles that I have installed. I'd rather see an icon than an empty space. 😉

Attempt to get favicon for RegExp match

---

background/openusercss-api.js
content/install-hook-openusercss.js
manifest.json

This PR adds a handshake between the site and Stylus.
Issue: #326 
Before merging: I haven't been able to get the content script to run in Firefox, but it does work in Chromium.

Add OpenUserCSS support

---

vendor-overwrites/csslint/parserlib.js

show invalid :not() as a nonfatal error

---

background/style-via-api.js

Fix: TypeError in style-via-api

---

.github/ISSUE_TEMPLATE.md

It should help debug the issue.

Chore: include stylus version in the issue template

---

background/background.js
background/db.js
background/style-manager.js
manage/import-export.js

This should improve the performance when importing backup. @narcolepticinsomniac

Add: don't re-open the connection when importing backup

---

js/msg.js

Since we have changed most of the background API calls from `sendMessage` to `API.someFn`, the optimization to message passing becomes meaningless.
This PR removes the optimization, which also frees us from https://github.com/openstyles/stylus/issues/541#issuecomment-436631824.

Change: simplify msg.js

---

content/apply.js

Fix: detect style CSP

---

edit/edit.js
edit/sections-editor.js
edit/source-editor.js

Fix dirty style updating. Closes #585

---

content/apply.js

I hope this can fix #577. It will also help if @AmpliDude and @miniBill can test this branch.

Change: defer page script injection. Try to inject to head

---

install-usercss.html
install-usercss/install-usercss.css
install-usercss/install-usercss.js

Previously all contents were replaced by text. This PR adds the text to the included span for both the update url and live reload blocks.

Fix usercss install error. Closes #589

---

popup/search-results.js

webRequest API can spoof Referer header directly so there's no need for the monstrous iframe workaround.

spoof HTTP Referer for USO directly

---

popup/popup.js

The configure icon code was spread out and confusing. This PR combines and cleans it up.

Fix & cleanup config in popup. Closes #602

---

content/install-hook-userstyles.js

Tested in Chrome 49, Chrome 70, FF 63.

Fix: remove unused code

---

background/style-manager.js

Change: don't wait when broadcasting messages

---

content/apply.js

Fix: catch syntax error

---

background/background.js

Fix: handle editDeleteText message

---

edit/sections-editor.js

Fixes #643.
@narcolepticinsomniac you may want to test this branch.

Fix: update live preview when the style is toggled/replaced

---

background/background.js
content/apply.js

Fix: return true in icon API

---

content/apply.js
content/style-injector.js
edit.html
install-usercss.html
manage.html
manifest.json
options.html
popup.html

Refactor: rewrite style injector

---

content/apply.js

8's fix - closes #706, closes #707

Avoid potential transition patch conflicts

---

content/apply.js
content/style-injector.js

Fix: change disabled state after the content is set

---

background/update.js

Fix: onAlarms is registered multiple times

---

content/install-hook-userstyles.js

Change: report updatable after the install button is prepared. Prevent installing duplicated styles from USO

---

_locales/en/messages.json
background/style-manager.js
popup/popup.css
popup/popup.js

Revert to eight04's initial two commits in #681 which make exclusion toggles domain and singular URLs only, plus reincorporate the js menu height calculation.

Simplify exclusions

---

background/db.js
js/polyfill.js

Fix: db initializing error, polyfill localStorage/sessionStorage

---

edit/edit.css

Fix: single editor doesn't stretch to full height

---

popup.html
popup/popup.css
popup/popup.js

I think it's better in general, and also eliminates the glitchiness of expandable menus in FF, not to mention possible scroll issues on long style lists with overflow, plus the fact that we could add many menu items in the future without the menu looking ridiculous.
IDEK how the formatting got screwed up and borked the diffs in the other PR. I updated my editor config plugin, so let's see if that helps. I restarted with a fresh master and copy/pasted the changes, so if it's still screwy, I guess my editor needs more help. If not, I'm not playing around with it anymore right now, and the other PR does at least work.

menus as dialogs

---

content/apply.js

Closes #756
I edited this a couple days ago, so let's double check the diff and make sure I didn't screw anything up.

Revert defer page script injection

---

js/msg.js

Enhance: faster msg.sendBg

---

content/apply.js
package.json

Reverts openstyles/stylus#758
Fixes #577

Change: a better way to defer page script injection, switch to inline script

---

js/usercss.js

Fix: don't assign undefined to style object

---

content/apply.js

Change: check style.sheet instead of getComputedStyle

---

_locales/en/messages.json
popup.html
popup/popup.css
popup/popup.js

This will stop adding soft-hyphens within the popup. See #312 comments.

Fix word breaks in popup

---

edit/global-search.js

fix an infinite loop in editor search with /^/ or /$/

---

_locales/en/messages.json
background/background.js
manifest.json

Adds option to reload extension in the context menu if not installed from extension gallery. Any objections or corrections?

Add reload context menu item

---

background/content-scripts.js

Didn't really test it, just wrote the fix based by the symptoms described in https://github.com/openstyles/stylus/pull/843#discussion_r377807448: the reinjector will wait for the tabs to finish loading before pinging them.
>When the browser starts, there is a chance that the pong callback/content script is not available yet but the background script started pinging. As a result, content scripts defined in manifest are injected and background also tries to inject content scripts again. Therefore the error occurs.
>I guess this can be produced consistently if there is a heavy processing content script (which can be injected by other extensions) is injected before `apply.js`.

wait for tabs to load when reinjecting

---

background/content-scripts.js

Follow-up to #849 which missed the deadline.

also handle removed/replaced/errored tabs in injectToAllTabs

---

background/token-manager.js
package-lock.json

Fix: Onedrive sync is broken on Firefox

---

edit/edit.css

set min-height outside of query

---

background/background.js

My bad, always forget to reference the relevant issue. Closes #898
I didn't exactly test it extensively, but it seems to do the trick.

fix FF shortcuts button

---

vendor-overwrites/colorpicker/colorview.js

Fixes a longstanding bug.
~Alleviates #888.~
~Theoretically this bug could be the sole culprit of that issue.~ Alas, no.

fix infinite loop in colorizeInvisible

---

edit/edit.css

Path of least resistance. Scrollbars are handier when they work. Closes #899 
Anybody feels like debugging FF instead, have at it. If that doesn't happen sometime in the near future, this is it.

CM scrollbar pointer-events

---

manage/manage.js
options/options.js

Fixes #822
Max version Dropbox disable and no sync pull animations.

Max version Dropbox disable and no sync pull animations

---

edit/codemirror-default.js

add ":" to prop names in css autocomplete menu

---

js/messaging.js

Turns out xhr.timeout applies to the entire process, not just to the establishing of a connection, so this PR adds a separate loadTimeout for the actual data transfer.
Fixes #929.

use a separate loadTimeout for the actual data transfer

---

manage/incremental-search.js

Fixes #934 presumably (I was able to read only the title).

focus search field on Ctrl-F in manager

---

vendor-overwrites/csslint/parserlib.js

Fixes for csslint parserlib

---

_locales/ko/messages.json

Korean translation

---

manage/import-export.js
manage/manage.js

throttle DOM updates in manager while importing

---

vendor-overwrites/csslint/parserlib.js

csslint: Selectors L4 parts (ED 2020-04-07)

---

content/style-injector.js

Fixes the bug introduced in #990.

update the style list after DOM

---

edit/global-search.css

show all spaces in find input in firefox

---

edit/source-editor.js
js/dom.js

use mousewheel to change focused "input[type=number], select"

---

edit/source-editor.js

Fix: enable linter after processing metadata

---

content/apply.js

fix styling of options frame in FF

---

_locales/en/messages.json
manage.html
manage/import-export.js
manage/manage.css
manage/manage.js

Fixes #1019
Switch back to buttons for import/export, and add a sync button for discoverability, which simply opens options.

Remove deprecated dropbox and add sync button

---

vendor-overwrites/csslint/parserlib.js

Now even the unknown @-rules are consumed as they should be.
Inspired by the [new `@property` rule](https://developers.google.com/web/updates/2020/08/nic85#css-properties).
```css
@-moz-document domain("bing.com") {
@foo bar;
@property --colorPrimary {    
syntax: '<color>';  
initial-value: magenta;
inherits: false;
}
}
```

parserlib: consume unknown @-rules per CSS grammar

---

package-lock.json
package.json
vendor/codemirror/README.md
vendor/codemirror/addon/lint/lint.css
vendor/codemirror/addon/lint/lint.js
vendor/codemirror/keymap/vim.js
vendor/codemirror/lib/codemirror.css
vendor/codemirror/lib/codemirror.js
vendor/codemirror/mode/javascript/javascript.js

Seems fine so far but let's test it a bit more, just in case.

CodeMirror 5.58.0

---

background/background-worker.js

Fixes #995.
@silverwind, it'd be helpful if you could test it in various combinations of preprocessors and color types.

convert colors in `uso` preprocessor to hex/rgb same as USO site

---

options/options.js

remove dropbox disabled

---

background/style-manager.js
js/sections-util.js

ignore empty code only in global (non-targeted) sections

---

content/install-hook-usercss.js
install-usercss/install-usercss.js

process current contents when live-reload is enabled

---

.eslintrc.yml
_locales/en/messages.json
background/background-worker.js
background/background.js
background/db.js
background/style-manager.js
background/usercss-helper.js
background/usercss-install-helper.js
edit/editor-worker.js
edit/source-editor.js
install-usercss/install-usercss.js
js/dom.js
js/messaging.js
js/polyfill.js
manifest.json
popup.html
popup/hotkeys.js
popup/popup.js
popup/search-results.css
popup/search-results.js

Fixes #926.
Fixes #420 - Search by text and sort the results.
Seems to work but didn't test it a lot yet.

switch to USO-archive for inline search in popup

---

background/background.js
background/token-manager.js
content/install-hook-userstyles.js
edit/codemirror-default.css
edit/edit.css
edit/edit.js
edit/linter-config-dialog.js
edit/live-preview.js
edit/sections-editor-section.js
global.css
install-usercss/install-usercss.css
install-usercss/install-usercss.js
js/dom.js
js/polyfill.js
js/router.js
js/script-loader.js
manage/incremental-search.js
manage/manage.css
manage/manage.js
msgbox/msgbox.css
msgbox/msgbox.js
options/onoffswitch.css
options/options.js
popup/hotkeys.js
popup/popup.css
popup/popup.js
popup/search-results.css
popup/search-results.js
vendor-overwrites/colorpicker/colorpicker.css
vendor-overwrites/colorpicker/colorpicker.js

* hide focus outline on a lone section
WDYT?
* also apply live-preview if an unsaved style was disabled - useful in case live-preview was disabled at first, then after some editing you uncheck `[ ] enabled` (or press Alt-Enter), and enable live-preview to see how the site looks without the style applied.

tweak editor

---

edit/colorpicker-helper.js
vendor-overwrites/colorpicker/colorpicker.css
vendor-overwrites/colorpicker/colorpicker.js
vendor-overwrites/colorpicker/colorview.js

Click = use the color.
Hover = view the color and line numbers.
Right-click = scroll the editor to the next occurrence.

show a palette for current editor in color picker

---

background/update-manager.js
manage/manage.css

Fixes #892.
~Fixes 1122.~
@eight04 if you'd like to review, here's a simpler PR extracted from that monster.

async'ify update.js + metacss + uso2usercss

---

background/token-manager.js
js/toolbox.js
popup/preinit.js

vivaldi bug workaround: open webAuth flow in a tab

---

edit/autocomplete.js
edit/editor-worker.js
js/csslint/parserlib.js

Fixes #1162.
Let's test/polish it.

try to show applicable values in autocomplete for props

---

popup/popup.css

fix flicker when hovering buttons in popup [Firefox]

---

background/token-manager.js
content/install-hook-userstylesworld.js

- Changes the necessary endpoints for OAuth to newer ones that make more sense.
- Related commit on USw: https://github.com/userstyles-world/userstyles.world/commit/cf6384cf4dacfb3a1894a2a7bf5e64e2fdfb8d07

Change USw endpoints

---

js/dlg/message-box.css
manage/import-export.js
manage/updater-ui.js

- Resolves #1270
- See details on the issue mentioned.
Fixed screenshot:

Use flex to center #message-box

---

js/dlg/message-box.css
js/dlg/message-box.js

- Allows the message box to be dragged to any position on the screen, so the user can set it to their wishes.
- Something as discussed in #1270.

Allow dragging the message box

---

background/sync-manager.js

randomize sync interval to avoid infinite deadlocks

---

background/style-manager.js
edit.html
js/prefs.js

Fix integration

---

background/style-manager.js
background/token-manager.js
content/install-hook-userstylesworld.js

It will now simply pass the vendor_data query which will exposed on the `location.search` once you are on the `/api/oauth/style/new` path. And thus can be retrieved which styleID should be need to get.
Related USw commit: https://github.com/userstyles-world/userstyles.world/commit/59b2eb8f3afec8b8cf8efc92c7b8d15d1e3b6fe9
@tophf You can get the [patch file](https://github.com/openstyles/stylus/pull/1288.patch) if you'd like and apply it to your existing PR.

Don't rely on _isUswLinked

---

install-usercss.html
install-usercss/install-usercss.css
install-usercss/install-usercss.js
js/dlg/config-dialog.css
js/dlg/config-dialog.js
js/dlg/message-box.js

show config for usercss vars in installer

---

popup/search.css
popup/search.js

Errors during installation will be shown inline so the user can retry by clicking the thumbnail again.
Thoughts/objections on the appearance?
@narcolepticinsomniac?

show installation error inline, allow retrying

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/bug_report.md

- Add a CSS section(so I don't have to see those comments about posting CSS etc).
- Make it into more sections and separate them.
- Add notes to each section.
@narcolepticinsomniac this is what I had in mind.

Improve issue template

---

edit/edit.css
edit/regexp-tester.js

Fixes #1331.
The problem was the absolutely positioned icons.

fix regexp report overflow

---

content/apply.js

Fixes https://github.com/openstyles/stylus/issues/865#issuecomment-925721885

fix iframe visibility detection

---

background/style-manager.js
js/csslint/parserlib.js
js/sections-util.js
js/usercss-compiler.js

fixes #1347
@Gusted, it'd be helpful if you test it...

add vars after `@import` in compiled code

---

edit.html
edit/settings.css
edit/settings.js

@eight04, check this out and see if you can suggest improvements for `placeholder`.

autosize textareas in style settings

---

background/style-manager.js
edit/settings.js
popup/popup.js

Add: support inclusions

---

_locales/en/messages.json
background/sync-manager.js
options.html
options/options.css
options/options.js

Add: webdav sync

---

.gitignore
background/usercss-install-helper.js

Fix: compatible with kiwi

---

_locales/en/messages.json
edit.html
edit/edit.css
edit/edit.js
edit/source-editor.js
global.css
js/dom-on-load.js
js/dom.js
js/localization.js

Fixes #896.
Agonized for a while as to where to put the button. Went with `Editor settings` because this feature is rarely used and is kinda about customizing the editor.
Screenshots:
<details><summary>Normal mode</summary>
</details>
<details><summary>Compact mode</summary>
</details>

save-as-template button in editor

---

background/update-manager.js
edit/settings.css
edit/settings.html
edit/settings.js
install-usercss/install-usercss.js
js/dom.js

add per-style setting for autoupdate checks

---

global.css
popup.html
popup/popup.css
popup/popup.js

* switched to pure CSS flex+order instead of JS
* moved the main buttons to the top

fix split-btn with popup.stylesFirst

---

background/sync-manager.js

Fixes #1447.
@eight04, could you test this? I never used nextcloud...

fix nextcloud WebDAV csrf error

---

background/common.js
background/db.js
background/style-manager.js
background/sync-manager.js

fix null doc in sync for injectionOrder

---

background/style-manager.js
edit/edit.js
package-lock.json

Fix: update preview when config change

---

src/css/global-dark.css
src/css/global.css

https://github.com/user-attachments/assets/67a30d68-125d-49a4-9f19-2a61639f5d65

Range slider accent color

---

src/js/dom-util.js

chore: update dom-util.js
